# Hello World of Tensorflow

In [5]:

#import block
import tensorflow as tf

#graph definition

'''In the present case, our graph consists of only one node, the
tensor constant message consisting of byte string. '''

message=tf.constant('Welcome to the exciting world of deep neural networks')

#running the computational graoh
with tf.Session() as sess:
    print(sess.run(message).decode())   #This says that the result is a byte string . To remove string quotes and b (for byte), we
#use the method decode() .
    

Welcome to the exciting world of deep neural networks


## Adding two number using tensorflow


In [6]:
# adding two vectors using tensorflow

v_1=tf.constant([1,2,3,4])      #vector 1
v_2=tf.constant([5,6,7,8])      # vector 2
v_add=tf.add(v_1, v_2)
with tf.Session() as sess:
    print(sess.run(v_add))
    
    
# another way of doing it one line is: 
print(tf.Session().run(tf.add(tf.constant([1,2,3,4]),tf.constant([5,6,7,8])
)))
#consider that the second method requires more memory than the first one and make the code more complicated to run


#using interactive session


'''InteractiveSession makes itself the
default session so that you can directly call run the tensor Object using eval() without
explicitly calling the session
'''
sess=tf.InteractiveSession()
v_1=tf.constant([1,2,3,4])      #vector 1
v_2=tf.constant([5,6,7,8])      # vector 2
v_add=tf.add(v_1, v_2)
print(v_add.eval())
sess.close()


[ 6  8 10 12]
[ 6  8 10 12]
[ 6  8 10 12]



## INTRODUCTION TO PLACEHOLDERS

placeholders, they are used to feed data to the graph. We can define a placeholder
using the following:

tf.placeholder(dtype, shape=None, name=None)'''


In [8]:
#here, name is given so that we can see the required placeholders with that name in Tensorboard

x=tf.placeholder(tf.float32, name='X')
y=tf.placeholder(tf.float32, name='Y')

## Working with constants, variables and placeholders

In [9]:
t_1=tf.constant(4)          #declare a scalar constant
t_2=tf.constant([4,2,3])    #declare a vector constant
zero_t=tf.zeros([4,3], tf.int32)    #declare a matrix with zeros of size (4*3)
ones_t=tf.ones([4,3], tf.int32)     #declare a matrix with ones of size (4*3)

zero_t1=tf.zeros_like(t_2)        #giving dimension same as that of t_2
ones_t2=tf.ones_like(t_2)         #giving dimension same as that of t_2
    
range_t = tf.linspace(2.0,5.0,5)  #creating a sequence of evenly spaced vectors 

range_t1=tf.range(10,100, 10)   #not including the end limit, we use the fucntion range

#creating random tensors from normal distribution
t_random=tf.random_normal([2,3], mean=2.0, stddev=4.0, seed=12)

#creating random tensors from truncated normal distribution
t_random1=tf.truncated_normal([2,3], stddev=2.0, seed=12)     #default mean=0.0


#to randomly crop a given tensor
t_random_crop=tf.random_crop(t_random,[2,2],seed=12) 

#to randomly shuffle a tensor
t_random_shuffle=tf.random_shuffle(t_random,seed=12)

#T0 generate random variables
#variable are often used to generate weights and biases in neural network
rand_t=tf.random_uniform([50,50], 0, 10, seed=0)  #minval=0, maxval=10
var_t1=tf.Variable(rand_t)
var_t2=tf.Variable(rand_t)                          


#each variable must be initialized explicitly
initial_op=tf.global_variables_initializer()

#code example to define weights and biases
weights=tf.Variable(tf.random_normal([50,50], stddev=2))

 
biases=tf.Variable(tf.zeros([100]))


#initializaton of variables using variables
weights2=tf.Variable(weights.initialized_value(), name= 'w2')

with tf.Session() as sess:
    print(sess.run(rand_t))
    
    
#initialization during the running graph
bias = tf.Variable(tf.zeros([100,100]))
'''with tf.Session() as sess:
    print(sess.run(bias.initializer))'''
    
    
    
# Saving the variable
saver=tf.train.Saver()


x=tf.placeholder("float")
y=2*x
data=tf.random_uniform([4,5], 10)   #10 is the max value , 0 = minvalue
with tf.Session() as sess:
    x_data=sess.run(data)
    print(sess.run(y, feed_dict={x:x_data}))

    


[[1.0086262  9.701668   8.487642   ... 4.014183   4.2018986  6.0311484 ]
 [1.6479492  2.5117612  8.651404   ... 3.8982236  1.9020462  2.1089745 ]
 [0.5706465  5.807663   7.647709   ... 6.8128204  6.302782   2.469287  ]
 ...
 [4.303278   9.856594   8.3518715  ... 1.6166127  5.4081845  3.8831007 ]
 [7.8500056  0.83293796 3.787043   ... 7.4345884  9.469841   1.8955421 ]
 [2.594589   7.143749   3.7885928  ... 7.219738   2.5857759  9.880056  ]]
[[13.815865  12.397886  11.142136   9.291828   9.154556 ]
 [15.318569  14.406989  11.41412   18.45556    4.622267 ]
 [ 2.0552006  7.9276524 19.074408  17.44141   13.575354 ]
 [15.312391  13.055338  14.979452  19.815119   8.250525 ]]
