# Hello World of Tensorflow

### Import Bock

In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [7]:
print(tf.__version__)

1.12.0


### Graph Definition

In the present case, our graph consists of only one node, the
tensor constant message consisting of byte string. 

In [8]:
message=tf.constant('Welcome to the exciting world of deep neural networks')
hello=tf.constant('Hello')
world=tf.constant('world')


In [10]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [12]:

# if we print the tensor "hello", it wont directky print the string. instead, it will print
print(hello)

Tensor("Const_3:0", shape=(), dtype=string)


In [ ]:
hello

### running the computational graph

In [15]:

with tf.Session() as sess:
    print(sess.run(message).decode()) #This says that the result is a byte string . To remove string quotes and b (for byte), we
#use the method decode() .

with tf.Session() as sess:
    result=sess.run(hello+world)
    

Welcome to the exciting world of deep neural networks


In [18]:
print(result)

#here, 'b' represents that it is represented as number of bits

b'Helloworld'


In [19]:
a=tf.constant(10)
b=tf.constant(20)

In [20]:
type(a)

tensorflow.python.framework.ops.Tensor

In [22]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [23]:
with tf.Session() as sess:
    result=sess.run(a+b)

In [25]:
result

30

## Working with matrices

In [26]:
fill_mat=tf.fill((4,4), 10)

In [27]:
myzeros=tf.zeros((4,4))


In [28]:
myones=tf.ones((4,4))

In [32]:
with tf.Session() as sess:
    print("\nprinting a 4*4 matrix with the number 10\n")
    print(sess.run(fill_mat))
    print("\nprint a 4*4 matrix with 0s\n")
    print(sess.run(myzeros))
    print("\nprinting a 4*$ matrix with 1s\n")
    print(sess.run(myones))


printing a 4*4 matrix with the number 10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

print a 4*4 matrix with 0s

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

printing a 4*$ matrix with 1s

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Adding two number



### adding two vectors using tensorflow

In [7]:


v_1=tf.constant([1,2,3,4])      #vector 1
v_2=tf.constant([5,6,7,8])      # vector 2
v_add=tf.add(v_1, v_2)
with tf.Session() as sess:
    print(sess.run(v_add))
    
     


[ 6  8 10 12]


### another way of doing it one line is:

In [9]:
print(tf.Session().run(tf.add(tf.constant([1,2,3,4]),tf.constant([5,6,7,8])
)))

#consider that the second method requires more memory than the first one and make the code more complicated to run


[ 6  8 10 12]


### using interactive session


InteractiveSession makes itself the
default session so that you can directly call run the tensor Object using eval() without
explicitly calling the session


In [ ]:
 

sess=tf.InteractiveSession()
v_1=tf.constant([1,2,3,4])      #vector 1
v_2=tf.constant([5,6,7,8])      # vector 2
v_add=tf.add(v_1, v_2)
print(v_add.eval())
sess.close()



## INTRODUCTION TO PLACEHOLDERS

placeholders, they are used to feed data to the graph. We can define a placeholder
using the following:

tf.placeholder(dtype, shape=None, name=None)'''


In [8]:
#here, name is given so that we can see the required placeholders with that name in Tensorboard

x=tf.placeholder(tf.float32, name='X')
y=tf.placeholder(tf.float32, name='Y')

## Working with constants, variables and placeholders

### Working with constants

In [10]:
t_1=tf.constant(4)          #declare a scalar constant
t_2=tf.constant([4,2,3])    #declare a vector constant
zero_t=tf.zeros([4,3], tf.int32)    #declare a matrix with zeros of size (4*3)
ones_t=tf.ones([4,3], tf.int32)     #declare a matrix with ones of size (4*3)

zero_t1=tf.zeros_like(t_2)        #giving dimension same as that of t_2
ones_t2=tf.ones_like(t_2)         #giving dimension same as that of t_2
    
range_t = tf.linspace(2.0,5.0,5)  #creating a sequence of evenly spaced vectors 

range_t1=tf.range(10,100, 10)   #not including the end limit, we use the fucntion range

### Working with random numbers

In [11]:

#creating random tensors from normal distribution
t_random=tf.random_normal([2,3], mean=2.0, stddev=4.0, seed=12)

#creating random tensors from truncated normal distribution
t_random1=tf.truncated_normal([2,3], stddev=2.0, seed=12)     #default mean=0.0


#to randomly crop a given tensor
t_random_crop=tf.random_crop(t_random,[2,2],seed=12) 

#to randomly shuffle a tensor
t_random_shuffle=tf.random_shuffle(t_random,seed=12)


### Working with Variables

In [12]:

#T0 generate random variables
#variable are often used to generate weights and biases in neural network
rand_t=tf.random_uniform([50,50], 0, 10, seed=0)  #minval=0, maxval=10
var_t1=tf.Variable(rand_t)
var_t2=tf.Variable(rand_t)                          


#each variable must be initialized explicitly
initial_op=tf.global_variables_initializer()

#code example to define weights and biases
weights=tf.Variable(tf.random_normal([50,50], stddev=2))

 
biases=tf.Variable(tf.zeros([100]))



In [14]:


#initializaton of variables using Session
weights2=tf.Variable(weights.initialized_value(), name= 'w2')

with tf.Session() as sess:
    print(sess.run(rand_t))
    
    
#initialization during the running graph
bias = tf.Variable(tf.zeros([100,100]))
'''with tf.Session() as sess:
    print(sess.run(bias.initializer))'''
    
    
    
# Saving the variable
saver=tf.train.Saver()


    


[[1.0086262  9.701668   8.487642   ... 4.014183   4.2018986  6.0311484 ]
 [1.6479492  2.5117612  8.651404   ... 3.8982236  1.9020462  2.1089745 ]
 [0.5706465  5.807663   7.647709   ... 6.8128204  6.302782   2.469287  ]
 ...
 [4.303278   9.856594   8.3518715  ... 1.6166127  5.4081845  3.8831007 ]
 [7.8500056  0.83293796 3.787043   ... 7.4345884  9.469841   1.8955421 ]
 [2.594589   7.143749   3.7885928  ... 7.219738   2.5857759  9.880056  ]]


### Working with placeolders

Placeholders play an important role in tensorflow.
The data is stored and is to be feeded using placeholders only

In [15]:

x=tf.placeholder("float")
y=2*x
data=tf.random_uniform([4,5], 10)   #10 is the max value , 0 = minvalue
with tf.Session() as sess:
    x_data=sess.run(data)
    print(sess.run(y, feed_dict={x:x_data}))


[[19.284464   3.917202  19.66701   14.605167   7.319645 ]
 [ 6.4177914 10.786342  16.904617  19.33998    8.84497  ]
 [17.68161    9.200086  17.179434  13.050073  15.260157 ]
 [19.219875   2.9081955 12.569159  17.6507     4.677763 ]]
